# example: docker build -t jojons/ngx-admin-node-modules-demo:4.0.1.0 -f Dockerfile.ngx-admin-node-modules .
FROM node:10.18.0-buster AS deps
WORKDIR /deps
COPY ./package.json .
RUN npm i -g npm@latest && npm install
# last works withnpm 6.13.4
